apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-netapp-ultra
  labels: 
    storage-tier: ultra
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.4
    path: "/hpcc-volume"

