apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-netapp
spec:
  selector: 
    matchLabels:
      storage-tier: ultra
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
