apiVersion: apps/v1
kind: Deployment
metadata:
  name: clippy
spec:
  selector:
    matchLabels:
      run: clippy
  replicas: 1
  template:
    metadata:
      labels:
        run: clippy
    spec:
      shareProcessNamespace: true
      containers:
      - name: dotnettools
        image: stevegriffith/dotnettools:6.0    
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      - name: clippy
        image: stevegriffith/clippyfunc:6.0
        # env:
        #   - name: COMPlus_gcServer
        #     value: "0"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clippy
  labels:
    run: clippy
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: clippy

