apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: resolvconf-edit
  labels:
    app: resolvconf-edit
spec:
  selector:
    matchLabels:
      name: resolvconf-edit
  template:
    metadata:
      labels:
        name: resolvconf-edit
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical      
      containers:
        - name: sed
          image: busybox
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/resolv
              name: etc
          command: [ "/bin/sh", "-c", "--" ]
          args: ["while true;do cp /host/resolv/resolv.conf /host/resolv/resolv.conf.new;sed -i ''s/irerif4b12cuxks0fjdgdjyfgh.bx.internal.cloudapp.net/griffithhomelab.net/g'' /host/resolv/resolv.conf.new;cp /host/resolv/resolv.conf.new /host/resolv/resolv.conf;sleep 60;done;"]
      volumes:
        - name: etc
          hostPath:
            path: /run/systemd/resolve/