apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  labels:
    deploymentName: myapp-http
spec:
  scaleTargetRef:
    name: webapp
  pollingInterval: 5
  cooldownPeriod:  10
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
      metricName: process_connections
      threshold: '10'
      query: sum(rate(haproxy_backend_loadbalanced_total[1m]))
