apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ALB1"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-lb1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-lb1
  name: nginx-lb1
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx-lb1
  strategy: {}
  template:
    metadata:
      labels:
        run: nginx-lb1
    spec:
      containers:
      - image: nginx
        name: nginx
